routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your donation. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache & Route is cleared";
});

// ------------------------ Front-End -------------------------------------
Route::get('/', 'frontend\Home@index')->name('index');
Route::get('/home', 'frontend\Home@index')->name('home');

Route::get('/about', 'frontend\About@index')->name('about');

Route::get('/news_acts/{page_num}', 'frontend\NewsActs@index')->name('news_acts');
Route::get('/news_acts/detail/{page_num}/{id}', 'frontend\NewsActs@detail')->name('news_acts_detail');
Route::get('/news_acts/detail/{id}/gallery', 'frontend\NewsActs@gallery')->name('news_acts_gallery');

Route::get('/contact', 'frontend\Contact@index')->name('contact');

Route::get('/donation', 'frontend\Donation@index')->name('donation');

Route::group(['middleware'=>['XSS']], function () { // ดัก script ใน Form
    Route::post('/contact_submit', 'frontend\Contact@contactSubmit')->name('contact_submit');
    Route::post('/donation_submit', 'frontend\Donation@donationSubmit')->name('donation_submit');
});

// ------------------------ .end Front-End -------------------------------------

// ------------------------ Back-End -------------------------------------
//Auth Routes
Auth::routes();
Route::prefix('/@backend')->name('auth.')->namespace('Admin\Auth')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.auth');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

// Admin manage route
Route::prefix('/@backend')->name('admin.')->namespace('Admin')->middleware('auth:admin')->group(function () {
    Route::get('/reset_password', 'ResetPasswordController@showResetPasswordForm')->name('reset_password');
    Route::post('/reset_password/update', 'ResetPasswordController@update')->name('reset_password.update');
    // Super Admin only
    Route::get('/admin_manage', 'ManageAdminsController@index')->name('admin_manage');
    Route::get('/admin_manage/create_form', 'ManageAdminsController@createForm')->name('admin_manage.create_form');
    Route::post('/admin_manage/create', 'ManageAdminsController@create')->name('admin_manage.create');
    Route::get('/admin_manage/edit_form/{id}', 'ManageAdminsController@editForm')->name('admin_manage.edit_form');
    Route::post('/admin_manage/edit', 'ManageAdminsController@edit')->name('admin_manage.edit');
    Route::get('/admin_manage/logging/{id}', 'LogsController@index')->name('admin_manage.logging');
});

Route::prefix('/@backend')->name('backend.')->namespace('backend')->middleware('auth:admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    // Home route
    Route::get('/home/banner_edit_form', 'HomeController@bannerEditForm')->name('home_banner_edit_form');
    Route::post('/home/banner_edit', 'HomeController@bannerEdit')->name('home_banner_edit');
    Route::get('/home/about_edit_form', 'HomeController@aboutEditForm')->name('home_about_edit_form');
    Route::post('/home/about_edit', 'HomeController@aboutEdit')->name('home_about_edit');
    Route::get('/home/help_edit_form', 'HomeController@helpEditForm')->name('home_help_edit_form');
    Route::post('/home/help_edit', 'HomeController@helpEdit')->name('home_help_edit');
    Route::get('/home/divider_edit_form', 'HomeController@dividerEditForm')->name('home_divider_edit_form');
    Route::post('/home/divider_edit', 'HomeController@dividerEdit')->name('home_divider_edit');
    // About us route
    Route::get('/about_us/banner_edit_form', 'AboutController@aboutBannerEditForm')->name('about_banner_edit_form');
    Route::post('/about_us/banner_edit', 'AboutController@aboutBannerEdit')->name('about_banner_edit');
    Route::get('/about_us/who_we_are_edit_form', 'AboutController@aboutWhoWeAreEditForm')->name('about_who_we_are_edit_form');
    Route::post('/about_us/who_we_are_edit', 'AboutController@aboutWhoWeAreEdit')->name('about_who_we_are_edit');
    Route::get('/about_us/what_we_do_edit_form', 'AboutController@aboutWhatWeDoEditForm')->name('about_what_we_do_edit_form');
    Route::post('/about_us/what_we_do_edit', 'AboutController@aboutWhatWeDoEdit')->name('about_what_we_do_edit');
    // News route
    Route::get('/news/banner_edit_form', 'NewsController@newsBannerEditForm')->name('news_banner_edit_form');
    Route::post('/news/banner_edit', 'NewsController@newsBannerEdit')->name('news_banner_edit');
    Route::get('/news_manage/{page_num}', 'NewsController@newsManage')->name('news_manage');
    Route::get('/news_manage/{page_num}/add_form', 'NewsController@addNewsForm')->name('news_add_form');
    Route::post('/news_manage/add', 'NewsController@addNews')->name('news_add');
    Route::get('/news_manage/{page_num}/edit_form/{id}', 'NewsController@newsEditForm')->name('news_edit_form');
    Route::post('/news_manage/edit', 'NewsController@newsEdit')->name('news_edit');
    // News route - dropzone upload image
    Route::post('/news_manage/upload_news_gallery', 'NewsController@uploadNewsImageDropzone')->name('upload_gallery_image');
    Route::post('/news_manage/load_news_gallery_list', 'NewsController@setImageListPreview')->name('load_news_gallery_list');
    Route::post('/news_manage/remove_news_gallery', 'NewsController@removeNewsGalleryImage')->name('delete_news_image_attache');
    // .end dropzone upload image
    Route::get('/news_manage/{page_num}/hide/{id}', 'NewsController@hideNews')->name('hide_news');
    Route::get('/news_manage/{page_num}/show/{id}', 'NewsController@showNews')->name('show_news');
    Route::get('/news_manage/{page_num}/remove/{id}', 'NewsController@removeNews')->name('remove_news');
    // Contact us route
    Route::get('/contact_us/banner_edit_form', 'ContactController@contactBannerEditForm')->name('contact_banner_edit_form');
    Route::post('/contact_us/banner_edit', 'ContactController@contactBannerEdit')->name('contact_banner_edit');
    Route::get('/contact_us/data_edit_form', 'ContactController@contactDataEditForm')->name('contact_data_edit_form');
    Route::post('/contact_us/data_edit', 'ContactController@contactDataEdit')->name('contact_data_edit');
    // Footer us route
    Route::get('/footer/edit_form', 'ContactController@footerEditForm')->name('footer_edit_form');
    Route::post('/footer/edit', 'ContactController@footerEdit')->name('footer_edit');
    // Donation route
    Route::get('/donation/banner_edit_form', 'DonationController@donationBannerEditForm')->name('donation_banner_edit_form');
    Route::post('/donation/banner_edit', 'DonationController@donationBannerEdit')->name('donation_banner_edit');
    Route::get('/donation/how_you_can_help_edit_form', 'DonationController@donationHowYouCanHelpEditForm')->name('donation_how_you_can_help_edit_form');
    Route::post('/donation/how_you_can_help_edit', 'DonationController@donationHowYouCanHelpEdit')->name('donation_how_you_can_help_edit');
    // Contact Person route
    Route::get('/contact_submit/list/{filter?}', 'ContactSubmitController@contactList')->name('contact_list');
    // Donation route
    Route::get('/donation_submit/list/{filter?}', 'DonationSubmitController@donationList')->name('donation_list');
    Route::get('/donation_submit/detail/{id}/{filter?}', 'DonationSubmitController@donationDetail')->name('donation_detail');

    // File Upload
    Route::get('/file_upload', 'FileUploadController@index')->name('file_upload');
    Route::post('/file_upload/upload', 'FileUploadController@fileUpload')->name('file_upload.upload');
    Route::get('/file_upload/download/{id}', 'FileUploadController@downloadFile')->name('file_upload.download');
    Route::get('/file_upload/remove/{id}', 'FileUploadController@removeFile')->name('file_upload.remove');
});

// ------------------------ .end Back-End -------------------------------------

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/frontend/Home.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\News;
use App\Content;

class Home extends Controller
{
    public function index()
    {
        $data['page_th'] = 'หน้าหลัก';
        $data['page_en'] = 'home';

        // banner & text overlay banner
        $data['banner_data'] = Content::where('ref_name', 'home_banner')->where('page', 'home')->first();
        // about us text
        $data['about_data'] = Content::where('ref_name', 'about_data')->where('page', 'home')->first();
        // help us text
        $data['help_us_data_eng'] = Content::where('ref_name', 'help_us_acc_eng')->where('page', 'home')->first();
        $data['help_us_data_th'] = Content::where('ref_name', 'help_us_acc_th')->where('page', 'home')->first();
        // image divider
        $data['image_divider'] = Content::where('ref_name', 'image_divider')->where('page', 'home')->first();

        $data['news_list'] = News::where('enable', 1)->orderBy('created_at', 'desc')->limit(4)->get();

        return view('frontend.home', $data);
    }
}

resources/views/backend/pages/home/about.blade.php
<!DOCTYPE html>
<html lang="th">

@include('backend.layouts.header')

<!-- Body -->

<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        @include('backend.layouts.topnav')
        @include('backend.layouts.sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> <i class="fas fa-home"></i> {{ $page_th }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{ route('backend.dashboard') }}">แผงควบคุม</a></li>
                                <li class="breadcrumb-item active">{{ $page_th }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
              <div class="card card-warning">
                <div class="card-header">
                  <h3 class="card-title">แก้ไขข้อมูล{{ $page_th }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form id="send_form" class="form-horizontal" action="{{ route('backend.home_about_edit') }}" onsubmit="onLoad()" method="post">
                  @csrf

                  <div class="container">
                    <div class="card-body">

                      <div class="form-group row mt-3">
                          <label class="col-xl-2 control-label">เปลี่ยนรูป About us 1</label>
                          <!-- Home Banner input -->
                          <div class="col-xl-5 col-xl-offset-5 text-center">
                              <strong>เลือกรูป About us 1 ใหม่ </strong><br><small>( ขนาด : 768 x 1125 px )</small>
                              <span tabindex="0" data-toggle="popover" data-trigger="hover" data-placement="right" data-title="นามสกุลไฟล์ที่อนุญาต " data-content="นามสกุล .jpg, .jpeg และ .png เท่านั้น ขนาดไม่เกิน 2 MB"
                                      data-html='true'>
                                        <i class="fas fa-info-circle text-warning" style="cursor: pointer"></i>
                                    </span>
                              <br />
                              <br />
                              <input type="file" class="custom-file-input" name="upload_input_about_us_1" id="upload_input_about_us_1" accept=".jpeg,.jpg,.png" style="padding-left:20px;padding-top:5px">
                              <label class="custom-file-label mx-auto text-left text-gray" for="upload_input_about_us_1" style="margin-top:60px;width:auto;max-width:345px">เลือกรูป</label>
                              @error('upload_input_about_us_1')
                              <span class="text-danger ml-2 mt-5" role="alert">
                                  <strong class="mt-5">{{ $message }}</strong>
                              </span>
                              @enderror

                              <!-- #hidden_image base64 -->
                              <input type="hidden" name="about_us_1_data" id="about_us_1_data">

                              <div class="text-center mt-4" style="margin-top:30px">
                                  <div id="upload_display_about_us_1" style="width:100%;"></div>
                              </div>
                          </div>
                          <!-- .end News image input -->

                          <!-- Old news image show -->
                          <div class="col-xl-5 text-center">
                              <strong>รูป About us 1 เดิม <small>กดที่รูปเพื่อดู</small></strong>
                              <br>
                              <div class="" id="grid2">
                                  <a href="{{ config('app.url') }}files_upload/contents/{{ $about_data->image_name }}" target="_blank" style="cursor: zoom-in">
                                      <img class="border border-secondary mt-2" src="{{ config('app.url') }}files_upload/contents/{{ $about_data->image_name }}" style="max-width: 400px;width:100%;margin-top:8px;margin-bottom:8px">
                                  </a>
                              </div>
                          </div>
                          <!-- .end Old news image show -->
                      </div>

                      <!-- About us text TH-->
                      <div class="col-12 px-0">
                          <label for="about_us_th_text" class="control-label">ข้อความ About us</label>
                          <textarea name="about_us_th_text" id="about_us_th_text" class="textarea" placeholder="ข้อความ About us TH"
                            style="width: 100%; height: 250px;">{!! $about_data->content_th !!}</textarea>
                          @error('about_us_th_text')
                          <span class="invalid-feedback ml-2" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                          @enderror
                      </div>
                      <!-- .end About us text TH -->

                      <!-- About us text EN -->
                      <div class="col-12 mt-3 px-0">
                          <textarea name="about_us_en_text" id="about_us_en_text" class="textarea" placeholder="ข้อความ About us EN"
                            style="width: 100%; height: 250px;">{!! $about_data->content_en !!}</textarea>
                          @error('about_us_en_text')
                          <span class="invalid-feedback ml-2" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                          @enderror
                      </div>
                      <!-- .end About us text EN -->

                      <div class="form-group row mt-3">
                          <label class="col-xl-2 control-label">เปลี่ยนรูป About us 2</label>
                          <!-- Home Banner input -->
                          <div class="col-xl-5 col-xl-offset-5 text-center">
                              <strong>เลือกรูป About us 2 ใหม่ </strong><br><small>( ขนาด : 768 x 430 px )</small>
                              <span tabindex="0" data-toggle="popover" data-trigger="hover" data-placement="right" data-title="นามสกุลไฟล์ที่อนุญาต " data-content="นามสกุล .jpg, .jpeg และ .png เท่านั้น ขนาดไม่เกิน 2 MB"
                                      data-html='true'>
                                        <i class="fas fa-info-circle text-warning" style="cursor: pointer"></i>
                                    </span>
                              <br />
                              <br />
                              <input type="file" class="custom-file-input" name="upload_input_about_us_2" id="upload_input_about_us_2" accept=".jpeg,.jpg,.png" style="padding-left:20px;padding-top:5px">
                              <label class="custom-file-label mx-auto text-left text-gray" for="upload_input_about_us_2" style="margin-top:60px;width:auto;max-width:345px">เลือกรูป</label>
                              @error('upload_input_about_us_2')
                              <span class="text-danger ml-2 mt-5" role="alert">
                                  <strong class="mt-5">{{ $message }}</strong>
                              </span>
                              @enderror

                              <!-- #hidden_image base64 -->
                              <input type="hidden" name="about_us_2_data" id="about_us_2_data">

                              <div class="text-center mt-4" style="margin-top:30px">
                                  <div id="upload_display_about_us_2" style="width:100%;"></div>
                              </div>
                          </div>
                          <!-- .end News image input -->

                          <!-- Old news image show -->
                          <div class="col-xl-5 text-center">
                              <strong>รูป About us 2 เดิม <small>กดที่รูปเพื่อดู</small></strong>
                              <br>
                              <div class="" id="grid3">
                                  <a href="{{ config('app.url') }}files_upload/contents/{{ $about_data->link_url }}" target="_blank" style="cursor: zoom-in">
                                      <img class="border border-secondary mt-2" src="{{ config('app.url') }}files_upload/contents/{{ $about_data->link_url }}" style="max-width: 400px;width:100%;margin-top:8px;margin-bottom:8px">
                                  </a>
                              </div>
                          </div>
                          <!-- .end Old news image show -->
                      </div>

                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <div class="container">
                      <button type="submit" id="submit_btn" class="btn btn-warning float-right">บันทึกการแก้ไข</button>
                    </div>
                  </div>
                  <!-- /.card-footer -->
                </form>
              </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        @include('backend.layouts.footer')

    </div>
    <!-- ./wrapper -->
</body>

<script type="text/javascript">
// Summernote
$('#about_us_th_text').summernote({
    height: 150,
    placeholder: 'กรอกข้อความ About us (ไทย)',
    lang: "th-TH",
    toolbar: [
        // ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'clear']],
        // ['fontname', ['fontname']],
        // ['color', ['color']],
        // ['para', ['ul', 'ol', 'paragraph']],
        // ['table', ['table']],
        // ['insert', ['link', 'picture', 'video']],
        // ['insert', ['picture', 'video']],
        ['view', ['fullscreen', 'codeview', 'help']],
    ],
});

// Summernote
$('#about_us_en_text').summernote({
    height: 150,
    placeholder: 'กรอกข้อความ About us (EN)',
    lang: "th-TH",
    toolbar: [
        // ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'clear']],
        // ['fontname', ['fontname']],
        // ['color', ['color']],
        // ['para', ['ul', 'ol', 'paragraph']],
        // ['table', ['table']],
        // ['insert', ['link', 'picture', 'video']],
        // ['insert', ['picture', 'video']],
        ['view', ['fullscreen', 'codeview', 'help']],
    ],
});

// Croppie for news image
$uploadCrop2 = $('#upload_display_about_us_1').croppie({
    enableExif: true,
    url: '{{ config('app.url') }}assets/dist/img/preview.jpg',
    viewport: {
        width: 257,
        height: 376.43,
        type: 'rectangle'
    },
    boundary: {
        width: 325,
        height: 450
    }
});

// Croppie for news image
$uploadCrop3 = $('#upload_display_about_us_2').croppie({
    enableExif: true,
    url: '{{ config('app.url') }}assets/dist/img/preview.jpg',
    viewport: {
        width: 257,
        height: 143.6,
        type: 'rectangle'
    },
    boundary: {
        width: 325,
        height: 220
    }
});

$('#upload_input_about_us_1').on('change', function() {
    var reader = new FileReader();
    reader.onload = function(e) {
        $uploadCrop2.croppie('bind', {
            url: e.target.result
        }).then(function() {
            console.log('ตัดครอปรูปแล้ว');
        });
    }
    reader.readAsDataURL(this.files[0]);
});

$('#upload_input_about_us_2').on('change', function() {
    var reader = new FileReader();
    reader.onload = function(e) {
        $uploadCrop3.croppie('bind', {
            url: e.target.result
        }).then(function() {
            console.log('ตัดครอปรูปแล้ว');
        });
    }
    reader.readAsDataURL(this.files[0]);
});

$("#submit_btn").click(function() {
    $uploadCrop2.croppie('result', {
        type: 'canvas',
        size: {
            width: 768
        }
    }).then(function(resp) {
        image = resp;
        $('#about_us_1_data').val(image);
        // console.log(resp);
    });

    $uploadCrop3.croppie('result', {
        type: 'canvas',
        size: {
            width: 768
        }
    }).then(function(resp) {
        image = resp;
        $('#about_us_2_data').val(image);
        // console.log(resp);
    });
});

// lightGallery plugin init
lightGallery(document.getElementById('grid2'), {
    selector: 'a',
    mode: 'lg-slide',
    cssEasing: 'cubic-bezier(0.25, 0, 0.25, 1)',
    width: '991px',
    thumbnail: true,
    animateThumb: true,
    showThumbByDefault: true,
    // iframeMaxWidth: 'auto',
    download: false,
    loop: true,
    zoom: true,
    scale: 1.8,
    fullScreen: true,
    // rotate: true
});

// lightGallery plugin init
lightGallery(document.getElementById('grid3'), {
    selector: 'a',
    mode: 'lg-slide',
    cssEasing: 'cubic-bezier(0.25, 0, 0.25, 1)',
    width: '991px',
    thumbnail: true,
    animateThumb: true,
    showThumbByDefault: true,
    // iframeMaxWidth: 'auto',
    download: false,
    loop: true,
    zoom: true,
    scale: 1.8,
    fullScreen: true,
    // rotate: true
});
</script>

</html>

resources/views/backend/pages/home/divider.blade.php
<!DOCTYPE html>
<html lang="th">

@include('backend.layouts.header')

<!-- Body -->

<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        @include('backend.layouts.topnav')
        @include('backend.layouts.sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> <i class="fas fa-home"></i> {{ $page_th }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{ route('backend.dashboard') }}">แผงควบคุม</a></li>
                                <li class="breadcrumb-item active">{{ $page_th }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
              <div class="card card-warning">
                <div class="card-header">
                  <h3 class="card-title">แก้ไขข้อมูล{{ $page_th }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form id="send_form" class="form-horizontal" action="{{ route('backend.home_divider_edit') }}" onsubmit="onLoad()" method="post">
                  @csrf

                  <div class="container">
                    <div class="card-body">

                      <div class="form-group row mt-3">
                          <label class="col-sm-2 control-label">เปลี่ยนรูปแบ่งส่วน</label>
                          <!-- Home Banner input -->
                          <div class="col-sm-10 text-center">
                              <strong>เลือกรูปแบ่งส่วนใหม่ </strong><br><small>( ขนาด : 1920 x 498 px )</small>
                              <span tabindex="0" data-toggle="popover" data-trigger="hover" data-placement="right" data-title="นามสกุลไฟล์ที่อนุญาต " data-content="นามสกุล .jpg, .jpeg และ .png เท่านั้น ขนาดไม่เกิน 2 MB"
                                      data-html='true'>
                                        <i class="fas fa-info-circle text-warning" style="cursor: pointer"></i>
                                    </span>
                              <br />
                              <br />
                              <input type="file" class="custom-file-input" name="upload_input_divider" id="upload_input_divider" accept=".jpeg,.jpg,.png" style="padding-left:20px;padding-top:5px">
                              <label class="custom-file-label mx-auto text-left text-gray" for="upload_input_divider" style="margin-top:60px;width:auto;max-width:345px">เลือกรูป</label>
                              @error('upload_input_help_us')
                              <span class="text-danger ml-2 mt-5" role="alert">
                                  <strong class="mt-5">{{ $message }}</strong>
                              </span>
                              @enderror

                              <!-- #hidden_image base64 -->
                              <input type="hidden" name="divider_data" id="divider_data">

                              <div class="text-center mt-4" style="margin-top:30px">
                                  <div id="upload_display_divider" style="width:100%;"></div>
                              </div>
                          </div>
                          <!-- .end News image input -->

                          <div class="col-sm-2">

                          </div>

                          <!-- Old news image show -->
                          <div class="col-sm-10 text-center">
                              <strong>รูปแบ่งส่วนเดิม <small>กดที่รูปเพื่อดู</small></strong>
                              <br>
                              <div class="" id="grid">
                                  <a href="{{ config('app.url') }}files_upload/contents/{{ $image_divider->image_name }}" target="_blank" style="cursor: zoom-in">
                                      <img class="border border-secondary mt-2" src="{{ config('app.url') }}files_upload/contents/{{ $image_divider->image_name }}" style="max-width: 768px;width:100%;margin-top:8px;margin-bottom:8px">
                                  </a>
                              </div>
                          </div>
                          <!-- .end Old news image show -->
                      </div>

                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <div class="container">
                      <button type="submit" id="submit_btn" class="btn btn-warning float-right">บันทึกการแก้ไข</button>
                    </div>
                  </div>
                  <!-- /.card-footer -->
                </form>
              </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        @include('backend.layouts.footer')

    </div>
    <!-- ./wrapper -->
</body>

<script type="text/javascript">
// Croppie for news image
$uploadCrop5 = $('#upload_display_divider').croppie({
    enableExif: true,
    url: '{{ config('app.url') }}assets/dist/img/preview.jpg',
    viewport: {
        width: 257,
        height: 66.65,
        type: 'rectangle'
    },
    boundary: {
        width: 325,
        height: 150
    }
});

$('#upload_input_divider').on('change', function() {
    var reader = new FileReader();
    reader.onload = function(e) {
        $uploadCrop5.croppie('bind', {
            url: e.target.result
        }).then(function() {
            console.log('ตัดครอปรูปแล้ว');
        });
    }
    reader.readAsDataURL(this.files[0]);
});

$("#submit_btn").click(function() {
    $uploadCrop5.croppie('result', {
        type: 'canvas',
        size: {
            width: 1920
        }
    }).then(function(resp) {
        image = resp;
        $('#divider_data').val(image);
        // console.log(resp);
    });
});

// lightGallery plugin init
lightGallery(document.getElementById('grid'), {
    selector: 'a',
    mode: 'lg-slide',
    cssEasing: 'cubic-bezier(0.25, 0, 0.25, 1)',
    width: '991px',
    thumbnail: true,
    animateThumb: true,
    showThumbByDefault: true,
    // iframeMaxWidth: 'auto',
    download: false,
    loop: true,
    zoom: true,
    scale: 1.8,
    fullScreen: true,
    // rotate: true
});
</script>

</html>