routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your donation. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache & Route is cleared";
});

// ------------------------ Front-End -------------------------------------
Route::get('/', 'frontend\Home@index')->name('index');
Route::get('/home', 'frontend\Home@index')->name('home');

Route::get('/about', 'frontend\About@index')->name('about');

Route::get('/news_acts/{page_num}', 'frontend\NewsActs@index')->name('news_acts');
Route::get('/news_acts/detail/{page_num}/{id}', 'frontend\NewsActs@detail')->name('news_acts_detail');
Route::get('/news_acts/detail/{id}/gallery', 'frontend\NewsActs@gallery')->name('news_acts_gallery');

Route::get('/contact', 'frontend\Contact@index')->name('contact');

Route::get('/donation', 'frontend\Donation@index')->name('donation');

Route::group(['middleware'=>['XSS']], function () { // ดัก script ใน Form
    Route::post('/contact_submit', 'frontend\Contact@contactSubmit')->name('contact_submit');
    Route::post('/donation_submit', 'frontend\Donation@donationSubmit')->name('donation_submit');
});

// ------------------------ .end Front-End -------------------------------------

// ------------------------ Back-End -------------------------------------
//Auth Routes
Auth::routes();
Route::prefix('/@backend')->name('auth.')->namespace('Admin\Auth')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.auth');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

// Admin manage route
Route::prefix('/@backend')->name('admin.')->namespace('Admin')->middleware('auth:admin')->group(function () {
    Route::get('/reset_password', 'ResetPasswordController@showResetPasswordForm')->name('reset_password');
    Route::post('/reset_password/update', 'ResetPasswordController@update')->name('reset_password.update');
    // Super Admin only
    Route::get('/admin_manage', 'ManageAdminsController@index')->name('admin_manage');
    Route::get('/admin_manage/create_form', 'ManageAdminsController@createForm')->name('admin_manage.create_form');
    Route::post('/admin_manage/create', 'ManageAdminsController@create')->name('admin_manage.create');
    Route::get('/admin_manage/edit_form/{id}', 'ManageAdminsController@editForm')->name('admin_manage.edit_form');
    Route::post('/admin_manage/edit', 'ManageAdminsController@edit')->name('admin_manage.edit');
    Route::get('/admin_manage/logging/{id}', 'LogsController@index')->name('admin_manage.logging');
});

Route::prefix('/@backend')->name('backend.')->namespace('backend')->middleware('auth:admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    // Home route
    Route::get('/home/banner_edit_form', 'HomeController@bannerEditForm')->name('home_banner_edit_form');
    Route::post('/home/banner_edit', 'HomeController@bannerEdit')->name('home_banner_edit');
    Route::get('/home/about_edit_form', 'HomeController@aboutEditForm')->name('home_about_edit_form');
    Route::post('/home/about_edit', 'HomeController@aboutEdit')->name('home_about_edit');
    Route::get('/home/help_edit_form', 'HomeController@helpEditForm')->name('home_help_edit_form');
    Route::post('/home/help_edit', 'HomeController@helpEdit')->name('home_help_edit');
    Route::get('/home/divider_edit_form', 'HomeController@dividerEditForm')->name('home_divider_edit_form');
    Route::post('/home/divider_edit', 'HomeController@dividerEdit')->name('home_divider_edit');
    // About us route
    Route::get('/about_us/banner_edit_form', 'AboutController@aboutBannerEditForm')->name('about_banner_edit_form');
    Route::post('/about_us/banner_edit', 'AboutController@aboutBannerEdit')->name('about_banner_edit');
    Route::get('/about_us/who_we_are_edit_form', 'AboutController@aboutWhoWeAreEditForm')->name('about_who_we_are_edit_form');
    Route::post('/about_us/who_we_are_edit', 'AboutController@aboutWhoWeAreEdit')->name('about_who_we_are_edit');
    Route::get('/about_us/what_we_do_edit_form', 'AboutController@aboutWhatWeDoEditForm')->name('about_what_we_do_edit_form');
    Route::post('/about_us/what_we_do_edit', 'AboutController@aboutWhatWeDoEdit')->name('about_what_we_do_edit');
    // News route
    Route::get('/news/banner_edit_form', 'NewsController@newsBannerEditForm')->name('news_banner_edit_form');
    Route::post('/news/banner_edit', 'NewsController@newsBannerEdit')->name('news_banner_edit');
    Route::get('/news_manage/{page_num}', 'NewsController@newsManage')->name('news_manage');
    Route::get('/news_manage/{page_num}/add_form', 'NewsController@addNewsForm')->name('news_add_form');
    Route::post('/news_manage/add', 'NewsController@addNews')->name('news_add');
    Route::get('/news_manage/{page_num}/edit_form/{id}', 'NewsController@newsEditForm')->name('news_edit_form');
    Route::post('/news_manage/edit', 'NewsController@newsEdit')->name('news_edit');
    // News route - dropzone upload image
    Route::post('/news_manage/upload_news_gallery', 'NewsController@uploadNewsImageDropzone')->name('upload_gallery_image');
    Route::post('/news_manage/load_news_gallery_list', 'NewsController@setImageListPreview')->name('load_news_gallery_list');
    Route::post('/news_manage/remove_news_gallery', 'NewsController@removeNewsGalleryImage')->name('delete_news_image_attache');
    // .end dropzone upload image
    Route::get('/news_manage/{page_num}/hide/{id}', 'NewsController@hideNews')->name('hide_news');
    Route::get('/news_manage/{page_num}/show/{id}', 'NewsController@showNews')->name('show_news');
    Route::get('/news_manage/{page_num}/remove/{id}', 'NewsController@removeNews')->name('remove_news');
    // Contact us route
    Route::get('/contact_us/banner_edit_form', 'ContactController@contactBannerEditForm')->name('contact_banner_edit_form');
    Route::post('/contact_us/banner_edit', 'ContactController@contactBannerEdit')->name('contact_banner_edit');
    Route::get('/contact_us/data_edit_form', 'ContactController@contactDataEditForm')->name('contact_data_edit_form');
    Route::post('/contact_us/data_edit', 'ContactController@contactDataEdit')->name('contact_data_edit');
    // Footer us route
    Route::get('/footer/edit_form', 'ContactController@footerEditForm')->name('footer_edit_form');
    Route::post('/footer/edit', 'ContactController@footerEdit')->name('footer_edit');
    // Donation route
    Route::get('/donation/banner_edit_form', 'DonationController@donationBannerEditForm')->name('donation_banner_edit_form');
    Route::post('/donation/banner_edit', 'DonationController@donationBannerEdit')->name('donation_banner_edit');
    Route::get('/donation/how_you_can_help_edit_form', 'DonationController@donationHowYouCanHelpEditForm')->name('donation_how_you_can_help_edit_form');
    Route::post('/donation/how_you_can_help_edit', 'DonationController@donationHowYouCanHelpEdit')->name('donation_how_you_can_help_edit');
    // Contact Person route
    Route::get('/contact_submit/list/{filter?}', 'ContactSubmitController@contactList')->name('contact_list');
    // Donation route
    Route::get('/donation_submit/list/{filter?}', 'DonationSubmitController@donationList')->name('donation_list');
    Route::get('/donation_submit/detail/{id}/{filter?}', 'DonationSubmitController@donationDetail')->name('donation_detail');

    // File Upload
    Route::get('/file_upload', 'FileUploadController@index')->name('file_upload');
    Route::post('/file_upload/upload', 'FileUploadController@fileUpload')->name('file_upload.upload');
    Route::get('/file_upload/download/{id}', 'FileUploadController@downloadFile')->name('file_upload.download');
    Route::get('/file_upload/remove/{id}', 'FileUploadController@removeFile')->name('file_upload.remove');
});

// ------------------------ .end Back-End -------------------------------------

resources/views/backend/pages/admin/admin_create.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('backend.layouts.header')

<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        @include('backend.layouts.topnav')
        @include('backend.layouts.sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"><i class="fas fa-user-plus"></i> {{ $page_th }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a onclick="onLoad('{{ route('admin.admin_manage') }}')" href="{{ route('admin.admin_manage') }}">จัดการผู้ดูแลเว็บ</a></li>
                                <li class="breadcrumb-item active">{{ $page_th }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="card card-warning">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fas fa-user-plus" style="margin-right:5px"></i> {{ $page_th }}</h3>
                        <button type="button" onclick="onLoad('{{ route('admin.admin_manage') }}')" class="btn btn-default btn-sm float-right">
                            <i class="fas fa-chevron-left"> ย้อนกลับ</i>
                        </button>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form id="created_admin" class="form-horizontal" action="{{ route('admin.admin_manage.create') }}" onsubmit="onLoad()" method="post">
                        @csrf

                        <div class="card-body container">
                            <div class="form-group row">
                                <label for="inputName" class="col-lg-2 control-label">ชื่อ<span class="text-danger"> *</span></label>
                                <div class="input-group col-lg-10">
                                    <input type="text" name="name" id="inputName" class="form-control @error('name') is-invalid @enderror" placeholder="ชื่อ" value="{{ old('name')}}" oninvalid="this.setCustomValidity('กรุณากรอกชื่อ')"
                                      oninput="this.setCustomValidity('')" required>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-user"></span>
                                        </div>
                                    </div>
                                    @error('name')
                                    <span class="invalid-feedback ml-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputEmail" class="col-lg-2 control-label">อีเมล<span class="text-danger"> *</span></label>
                                <div class="input-group col-lg-10">
                                    <input type="email" name="email" id="inputEmail" class="form-control @error('email') is-invalid @enderror" placeholder="อีเมล" value="{{ old('email') }}"
                                      oninvalid="this.setCustomValidity('กรุณากรอกอีเมลให้ถูกต้อง')" oninput="this.setCustomValidity('')" required>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-envelope"></span>
                                        </div>
                                    </div>
                                    @error('email')
                                    <span class="invalid-feedback ml-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-lg-2 control-label">รหัสผ่าน<span class="text-danger"> *</span></label>
                                <div class="input-group col-lg-10">
                                    <input name="password" type="password" id="inputPassword" class="form-control @error('password') is-invalid @enderror" placeholder="รหัสผ่าน (อย่างน้อย 6 ตัว)" value="{{ old('password') }}"
                                      oninvalid="this.setCustomValidity('กรุณากรอกรหัสผ่าน')" oninput="this.setCustomValidity('')" required>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-lock"></span>
                                        </div>
                                    </div>
                                    @error('password')
                                    <span class="invalid-feedback ml-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputConfirmPassword" class="col-lg-2 control-label">ยืนยันรหัสผ่าน<span class="text-danger"> *</span></label>
                                <div class="input-group col-lg-10">
                                    <input name="confirm_password" type="password" id="inputConfirmPassword" class="form-control @error('confirm_password') is-invalid @enderror" placeholder="กรอกรหัสผ่านอีกครั้ง" value="{{ old('confirm_password') }}"
                                      oninvalid="this.setCustomValidity('กรุณากรอกยืนยันรหัสผ่าน')" oninput="this.setCustomValidity('')" required>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-lock"></span>
                                        </div>
                                    </div>
                                    @error('confirm_password')
                                    <span class="invalid-feedback ml-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <!-- checkbox permission-->
                            <div class="form-group row">
                                <label for="pm_chk1" class="col-lg-2 control-label">สิทธิ์การเข้าใช้งาน<span class="text-danger"> *</span></label>
                                <div class="col-lg-10 clearfix">
                                    <div class="icheck-warning">
                                        <input class="form-check-input" type="checkbox" id="pm_chk1" name="admin_chk1">
                                        <label class="form-check-label" for="pm_chk1">จัดการผู้ดูแลเว็บ</label>
                                    </div>
                                    <div class="icheck-warning">
                                        <input class="form-check-input" type="checkbox" id="pm_chk2" name="admin_chk2">
                                        <label class="form-check-label" for="pm_chk2">ข้อมูลทั่วไป</label>
                                    </div>
                                    <div class="icheck-warning">
                                        <input class="form-check-input" type="checkbox" id="pm_chk3" name="admin_chk3">
                                        <label class="form-check-label" for="pm_chk3">ข่าวและกิจกรรม</label>
                                    </div>
                                    <div class="icheck-warning">
                                        <input class="form-check-input" type="checkbox" id="pm_chk4" name="admin_chk4">
                                        <label class="form-check-label" for="pm_chk4">ข้อมูลติดต่อและการบริจาค</label>
                                    </div>
                                    <small class="text-danger ml-2">
                                        <strong id="leastOnePermission"></strong>
                                    </small>
                                </div>

                            </div>
                            <!-- End checkbox permission-->

                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <div class="container">
                                <button type="submit" class="btn btn-warning float-right" onclick="return onClickCreate()">เพิ่มบัญชีผู้ดูแลเว็บ</button>
                                <button type="button" class="btn btn-secondary" onclick="onLoad('{{ route('admin.admin_manage') }}')">ยกเลิก</button>
                            </div>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>

            </section>
            <!-- /.content -->

        </div>
        <!-- /.content-wrapper -->

        @include('backend.layouts.footer')

    </div>
    <!-- ./wrapper -->

    <!-- Custom javascript for Admin create page -->
    <script type="text/javascript">
        function onClickCreate() {
            checked = $("input[type=checkbox]:checked").length;
            if ($('#inputName').val() == '' || $('#inputEmail').val() == '' || $('#inputPassword').val() == '' || $('#inputConfirmPassword').val() == '') {
                // return false;
            } else if (!checked && $('#inputName').val() != '' && $('#inputEmail').val() != '' && $('#inputPassword').val() != '' && $('#inputConfirmPassword').val() != '') {
                $('#leastOnePermission').text('กรุณาเลือกสิทธิ์อย่างน้อย 1 สิทธิ์');
                return false;
            } else {
                $('#loader_spinner').css('display', 'block');
                $("#created_admin").submit();
            }
        }
    </script>
    <!-- .end Custom javascript for Admin create page -->
</body>

</html>

resources/views/backend/pages/admin/admin_edit.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('backend.layouts.header')

<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

@include('backend.layouts.topnav')
@include('backend.layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark"><i class="fas fa-user-edit"></i> {{ $page_th }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('admin.admin_manage') }}" onclick="onLoad('{{ route('admin.admin_manage') }}')">จัดการผู้ดูแลเว็บ</a></li>
            <li class="breadcrumb-item active">{{ $page_th }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
      <section class="content">
        <div class="card card-warning">
          <div class="card-header">
            <h3 class="card-title">แก้ไขข้อมูลผู้จัดการเว็บ : {{ $admin_detail->name }}</h3>
            <span class="float-right">อัพเดตล่าสุด : {{ date('d/m/Y', strtotime($admin_detail->updated_at)) }} <i class="far fa-clock"></i> {{ date('H:i:s', strtotime($admin_detail->updated_at)) }}</span>
          </div>
          <!-- /.card-header -->
          <!-- form start -->
          <form id="send_form" class="form-horizontal" action="{{ route('admin.admin_manage.edit') }}" onsubmit="onLoad()" method="post">
            @csrf

            <div class="container">
              <div class="card-body">
                <div class="form-group row">
                  <label for="inputName" class="col-lg-2 control-label">ชื่อ</label>
                  <div class="input-group col-lg-10">
                    <input type="hidden" name="id" value="{{ $admin_detail->id }}"/>
                    <input type="text" name="admin_name" id="inputName" class="form-control" placeholder="ชื่อ" value="{{ $admin_detail->name }}">
                    <div class="input-group-append">
                      <div class="input-group-text">
                        <span class="fas fa-user"></span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="inputEmail" class="col-lg-2 control-label">อีเมล</label>
                  <div class="input-group col-lg-10">
                    <input type="email" name="admin_email" id="inputEmail" class="form-control"
                    placeholder="อีเมล" value="{{ $admin_detail->email }}" disabled>
                    <div class="input-group-append">
                      <div class="input-group-text">
                        <span class="fas fa-envelope"></span>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- checkbox permission-->
                <div class="form-group row">
                  <label class="col-lg-2 control-label">สิทธิ์การเข้าใช้งาน</label>
                  <div class="col-lg-10 clearfix">

                    <div class="icheck-warning">
                      <input class="form-check-input" type="checkbox" id="pm_chk1" name="admin_chk1"
                      @if($admin_detail->type) checked disabled
                      @elseif(!$admin_detail->type && $admin_detail->permission_1) checked
                      @endif>
                      @if($admin_detail->type)
                      <input type="hidden" name="admin_chk1" value="on">
                      @endif
                      <label class="form-check-label" for="pm_chk1">จัดการผู้ดูแลเว็บ</label>
                    </div>

                    <div class="icheck-warning">
                      <input class="form-check-input" type="checkbox" id="pm_chk2" name="admin_chk2"
                      @if($admin_detail->type) disabled checked value="on"
                      @elseif(!$admin_detail->type && $admin_detail->permission_2) checked
                      @endif>
                      @if($admin_detail->type)
                      <input type="hidden" name="admin_chk2" value="on">
                      @endif
                      <label class="form-check-label" for="pm_chk2">ข้อมูลทั่วไป</label>
                    </div>

                    <div class="icheck-warning">
                      <input class="form-check-input" type="checkbox" id="pm_chk3" name="admin_chk3"
                      @if($admin_detail->type) disabled checked value="on"
                      @elseif(!$admin_detail->type && $admin_detail->permission_3) checked
                      @endif>
                      @if($admin_detail->type)
                      <input type="hidden" name="admin_chk3" value="on">
                      @endif
                      <label class="form-check-label" for="pm_chk3">ข่าวและกิจกรรม</label>
                    </div>

                    <div class="icheck-warning">
                      <input class="form-check-input" type="checkbox" id="pm_chk4" name="admin_chk4"
                      @if($admin_detail->type) disabled checked value="on"
                      @elseif(!$admin_detail->type && $admin_detail->permission_4) checked
                      @endif>
                      @if($admin_detail->type)
                      <input type="hidden" name="admin_chk4" value="on">
                      @endif
                      <label class="form-check-label" for="pm_chk4">ข้อมูลติดต่อและการบริจาค</label>
                    </div>

                    @if(session('permission') != null)
                    <small class="text-danger">
                        <strong>{{ session('permission') }}</strong>
                    </small>
                    @endif

                  </div>
                </div>
                <!-- End checkbox permission-->

              </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
              <div class="container">
                <button type="submit" class="btn btn-warning float-right">บันทึกการแก้ไข</button>
                <button onclick="onLoad('{{ route('admin.admin_manage') }}')" type="button" class="btn btn-secondary">ยกเลิก</button>
              </div>
            </div>
            <!-- /.card-footer -->
          </form>
        </div>

      </section>
      <!-- /.content -->

</div>
<!-- /.content-wrapper -->

@include('backend.layouts.footer')

</div>
<!-- ./wrapper -->
<script type="text/javascript">
  // $(document).ready(
  //   // Summernote
  //   $('.textarea').summernote()
  // );
</script>
</body>
</html>

resources/views/backend/pages/admin/admin_manage.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('backend.layouts.header')

<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

@include('backend.layouts.topnav')
@include('backend.layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark"><i class="fas fa-users"></i> {{ $page_th }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <!-- <li class="breadcrumb-item"><a href="{{ route('backend.dashboard') }}">Home</a></li> -->
            <li class="breadcrumb-item active">{{ $page_th }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><b>ตาราง : ผู้ดูแลเว็บ</b> (จำนวน {{ $admins_num }} คน)</h3>

        <div class="card-tools">
          <button onclick="onLoad('{{ route('admin.admin_manage.create_form') }}')" type="button" class="btn btn-success">
            <i class="fas fa-plus" style="padding-right: 5px"></i> เพิ่มผู้ดูแลเว็บ</button>
        </div>
      </div>
      <div class="card-body">
        <table class="table table-responsive-xl table-hover">
            <thead>
              <tr>
                  <!-- <th style="width: 3%">ลำดับ</th> -->
                  <th style="width: auto">ชื่อ <small class="text-primary">(กดที่ชื่อเพื่อดูบันทึกการใช้งาน)</small></th>
                  <th style="width: 25%">สิทธิ์การเข้าถึง</th>
                  <th style="width: 25%">แก้ไขล่าสุด <small>&nbsp<i class="fas fa-arrow-up"></i></small></th>
                  <th style="width: 10%">แก้ไข</th>
              </tr>
            </thead>
            <tfoot>
                <tr>
                    <!-- <th style="width: 3%">ลำดับ</th> -->
                    <th style="width: auto">ชื่อ <small>(กดที่ชื่อเพื่อดูบันทึกการใช้งาน)</small></th>
                    <th style="width: 25%">สิทธิ์การเข้าถึง</th>
                    <th style="width: 25%">แก้ไขล่าสุด <small>&nbsp<i class="fas fa-arrow-up"></i></small></th>
                    <th style="width: 10%">แก้ไข</th>
                </tr>
            </foot>
            <tbody>

               <!-- Loop users table -->
               @foreach($admin_list as $row)
               <tr>
                   <td>
                     <ul class="list-inline">
                       <li class="list-inline-item time-line">
                         <i class="fas @if($row->type) fa-user-cog @else fa-user @endif text-gray-dark" style="font-size:2em"></i>
                       </li>
                       <a href="{{ route('admin.admin_manage.logging', $row->id) }}" target="_blank">
                       <li class="list-inline-item">
                         <p style="margin-top:-23px;position:absolute;background-color:#d9edf7;padding:2px 5px;border-radius:8px">{{ $row->name }} &nbsp;<i class="fas fa-external-link-alt" style="font-size: .7rem"></i> </p>
                       </li>
                      </a>
                     </ul>
                   </td>

                   <td>
                     <p>@if($row->type === 1) <b>Super Admin</b> @else Sub Admin @endif</p>
                   </td>

                   <td>
                       <p>{{ date('d/m/Y', strtotime($row->updated_at)) }}<br><i class="far fa-clock"></i> {{ date('H:i', strtotime($row->updated_at)) }}</p1>
                   </td>
                   <td class="project-actions text-left">
                     <a href="{{ route('admin.admin_manage.edit_form', $row->id) }}">
                     <button class="btn btn-warning btn-sm" onclick="onLoad('{{ route('admin.admin_manage.edit_form', $row->id) }}')">
                         <i class="fas fa-pencil-alt">
                         </i>
                         แก้ไข
                     </button>
                   </a>
                   </td>
               </tr>
               @endforeach
             <!-- End loop users table -->
            </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </section>
  <!-- /.content -->

</div>
<!-- /.content-wrapper -->

@include('backend.layouts.footer')

</div>
<!-- ./wrapper -->
<script type="text/javascript">
  // $(document).ready(
  //   // Summernote
  //   $('.textarea').summernote()
  // );
</script>
</body>
</html>