routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your donation. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache & Route is cleared";
});

// ------------------------ Front-End -------------------------------------
Route::get('/', 'frontend\Home@index')->name('index');
Route::get('/home', 'frontend\Home@index')->name('home');

Route::get('/about', 'frontend\About@index')->name('about');

Route::get('/news_acts/{page_num}', 'frontend\NewsActs@index')->name('news_acts');
Route::get('/news_acts/detail/{page_num}/{id}', 'frontend\NewsActs@detail')->name('news_acts_detail');
Route::get('/news_acts/detail/{id}/gallery', 'frontend\NewsActs@gallery')->name('news_acts_gallery');

Route::get('/contact', 'frontend\Contact@index')->name('contact');

Route::get('/donation', 'frontend\Donation@index')->name('donation');

Route::group(['middleware'=>['XSS']], function () { // ดัก script ใน Form
    Route::post('/contact_submit', 'frontend\Contact@contactSubmit')->name('contact_submit');
    Route::post('/donation_submit', 'frontend\Donation@donationSubmit')->name('donation_submit');
});

// ------------------------ .end Front-End -------------------------------------

// ------------------------ Back-End -------------------------------------
//Auth Routes
Auth::routes();
Route::prefix('/@backend')->name('auth.')->namespace('Admin\Auth')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.auth');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

// Admin manage route
Route::prefix('/@backend')->name('admin.')->namespace('Admin')->middleware('auth:admin')->group(function () {
    Route::get('/reset_password', 'ResetPasswordController@showResetPasswordForm')->name('reset_password');
    Route::post('/reset_password/update', 'ResetPasswordController@update')->name('reset_password.update');
    // Super Admin only
    Route::get('/admin_manage', 'ManageAdminsController@index')->name('admin_manage');
    Route::get('/admin_manage/create_form', 'ManageAdminsController@createForm')->name('admin_manage.create_form');
    Route::post('/admin_manage/create', 'ManageAdminsController@create')->name('admin_manage.create');
    Route::get('/admin_manage/edit_form/{id}', 'ManageAdminsController@editForm')->name('admin_manage.edit_form');
    Route::post('/admin_manage/edit', 'ManageAdminsController@edit')->name('admin_manage.edit');
    Route::get('/admin_manage/logging/{id}', 'LogsController@index')->name('admin_manage.logging');
});

Route::prefix('/@backend')->name('backend.')->namespace('backend')->middleware('auth:admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    // Home route
    Route::get('/home/banner_edit_form', 'HomeController@bannerEditForm')->name('home_banner_edit_form');
    Route::post('/home/banner_edit', 'HomeController@bannerEdit')->name('home_banner_edit');
    Route::get('/home/about_edit_form', 'HomeController@aboutEditForm')->name('home_about_edit_form');
    Route::post('/home/about_edit', 'HomeController@aboutEdit')->name('home_about_edit');
    Route::get('/home/help_edit_form', 'HomeController@helpEditForm')->name('home_help_edit_form');
    Route::post('/home/help_edit', 'HomeController@helpEdit')->name('home_help_edit');
    Route::get('/home/divider_edit_form', 'HomeController@dividerEditForm')->name('home_divider_edit_form');
    Route::post('/home/divider_edit', 'HomeController@dividerEdit')->name('home_divider_edit');
    // About us route
    Route::get('/about_us/banner_edit_form', 'AboutController@aboutBannerEditForm')->name('about_banner_edit_form');
    Route::post('/about_us/banner_edit', 'AboutController@aboutBannerEdit')->name('about_banner_edit');
    Route::get('/about_us/who_we_are_edit_form', 'AboutController@aboutWhoWeAreEditForm')->name('about_who_we_are_edit_form');
    Route::post('/about_us/who_we_are_edit', 'AboutController@aboutWhoWeAreEdit')->name('about_who_we_are_edit');
    Route::get('/about_us/what_we_do_edit_form', 'AboutController@aboutWhatWeDoEditForm')->name('about_what_we_do_edit_form');
    Route::post('/about_us/what_we_do_edit', 'AboutController@aboutWhatWeDoEdit')->name('about_what_we_do_edit');
    // News route
    Route::get('/news/banner_edit_form', 'NewsController@newsBannerEditForm')->name('news_banner_edit_form');
    Route::post('/news/banner_edit', 'NewsController@newsBannerEdit')->name('news_banner_edit');
    Route::get('/news_manage/{page_num}', 'NewsController@newsManage')->name('news_manage');
    Route::get('/news_manage/{page_num}/add_form', 'NewsController@addNewsForm')->name('news_add_form');
    Route::post('/news_manage/add', 'NewsController@addNews')->name('news_add');
    Route::get('/news_manage/{page_num}/edit_form/{id}', 'NewsController@newsEditForm')->name('news_edit_form');
    Route::post('/news_manage/edit', 'NewsController@newsEdit')->name('news_edit');
    // News route - dropzone upload image
    Route::post('/news_manage/upload_news_gallery', 'NewsController@uploadNewsImageDropzone')->name('upload_gallery_image');
    Route::post('/news_manage/load_news_gallery_list', 'NewsController@setImageListPreview')->name('load_news_gallery_list');
    Route::post('/news_manage/remove_news_gallery', 'NewsController@removeNewsGalleryImage')->name('delete_news_image_attache');
    // .end dropzone upload image
    Route::get('/news_manage/{page_num}/hide/{id}', 'NewsController@hideNews')->name('hide_news');
    Route::get('/news_manage/{page_num}/show/{id}', 'NewsController@showNews')->name('show_news');
    Route::get('/news_manage/{page_num}/remove/{id}', 'NewsController@removeNews')->name('remove_news');
    // Contact us route
    Route::get('/contact_us/banner_edit_form', 'ContactController@contactBannerEditForm')->name('contact_banner_edit_form');
    Route::post('/contact_us/banner_edit', 'ContactController@contactBannerEdit')->name('contact_banner_edit');
    Route::get('/contact_us/data_edit_form', 'ContactController@contactDataEditForm')->name('contact_data_edit_form');
    Route::post('/contact_us/data_edit', 'ContactController@contactDataEdit')->name('contact_data_edit');
    // Footer us route
    Route::get('/footer/edit_form', 'ContactController@footerEditForm')->name('footer_edit_form');
    Route::post('/footer/edit', 'ContactController@footerEdit')->name('footer_edit');
    // Donation route
    Route::get('/donation/banner_edit_form', 'DonationController@donationBannerEditForm')->name('donation_banner_edit_form');
    Route::post('/donation/banner_edit', 'DonationController@donationBannerEdit')->name('donation_banner_edit');
    Route::get('/donation/how_you_can_help_edit_form', 'DonationController@donationHowYouCanHelpEditForm')->name('donation_how_you_can_help_edit_form');
    Route::post('/donation/how_you_can_help_edit', 'DonationController@donationHowYouCanHelpEdit')->name('donation_how_you_can_help_edit');
    // Contact Person route
    Route::get('/contact_submit/list/{filter?}', 'ContactSubmitController@contactList')->name('contact_list');
    // Donation route
    Route::get('/donation_submit/list/{filter?}', 'DonationSubmitController@donationList')->name('donation_list');
    Route::get('/donation_submit/detail/{id}/{filter?}', 'DonationSubmitController@donationDetail')->name('donation_detail');

    // File Upload
    Route::get('/file_upload', 'FileUploadController@index')->name('file_upload');
    Route::post('/file_upload/upload', 'FileUploadController@fileUpload')->name('file_upload.upload');
    Route::get('/file_upload/download/{id}', 'FileUploadController@downloadFile')->name('file_upload.download');
    Route::get('/file_upload/remove/{id}', 'FileUploadController@removeFile')->name('file_upload.remove');
});

// ------------------------ .end Back-End -------------------------------------

app/Http/Controllers/backend/ContactSubmitController.php
<?php

namespace App\Http\Controllers\backend;

use Auth;

use App\ContactSubmit;
use App\Helper\DateHelper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactSubmitController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function isPermission()
    {
        if (!Auth::guard('admin')->user()->isPermission4()) {
            return Redirect::to('@backend/dashboard')->send()->with(array('alert' => 'toast','type' => 'error','message' => '&nbsp&nbsp คุณไม่ได้รับสิทธ์ให้เข้าถึง'));
        }
    }

    public function contactList()
    {
        $this->isPermission();

        // $per_page = 10;
        // $data['page_num'] = $page_num;

        $data['page_th'] = 'ข้อความการติดต่อ';
        $data['page_en'] = 'contact_list';
        $contact_list = ContactSubmit::orderBy('created_at', 'desc')->get();
        // dd($news_list->get());

        // $num_rows = $news_list->count();
        // // Paginate news_list
        // $news_list = $news_list->paginate($per_page, ['*'], 'page', $page_num);
        $new_contactArray = array();
        foreach ($contact_list as $row) {
            $row['created_datetime'] = DateHelper::dateToThaiFormat($row['created_at']);
            array_push($new_contactArray, $row);
        }
        $data['contact_list'] = $new_contactArray;
        // $data['max_page'] = ceil($num_rows / $per_page);
        //
        // if ($page_num > $data['max_page'] && $data['max_page'] != 0) {
        //     return redirect()->route('backend.news_manage', $data['max_page']);
        // }

        return view('backend.pages.contact_submit.contact_list', $data);
    }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function isPermission()
    {
        if (!Auth::guard('admin')->user()) {
            return Redirect::to('@backend/dashboard')->send()
            ->with(
                array(
              'alert' => 'toast',
              'type' => 'warning',
              'message' => '&nbsp&nbsp คุณไม่ได้รับสิทธ์ให้เข้าถึง')
            );
        }
    }

    public function index()
    {
        $this->isPermission();

        $data['page_th'] = 'แผงควบคุม';
        $data['page_en'] = 'dashboard';
        $data['admin_name'] = Auth::guard('admin')->user()->name;

        return view('backend.pages.dashboard', $data);
    }
}

app/Http/Controllers/backend/DonationSubmitController.php
<?php

namespace App\Http\Controllers\backend;

use Auth;

use App\DonationSubmit;
use App\Bank;
use App\Helper\DateHelper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DonationSubmitController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function isPermission()
    {
        if (!Auth::guard('admin')->user()->isPermission4()) {
            return Redirect::to('@backend/dashboard')->send()->with(array('alert' => 'toast','type' => 'error','message' => '&nbsp&nbsp คุณไม่ได้รับสิทธ์ให้เข้าถึง'));
        }
    }

    public function donationList()
    {
        $this->isPermission();

        // $per_page = 10;
        // $data['page_num'] = $page_num;

        $data['page_th'] = 'ข้อมูลการบริจาค';
        $data['page_en'] = 'donation_list';
        $donation_list = DonationSubmit::orderBy('created_at', 'desc')->get();
        // dd($news_list->get());

        // $num_rows = $news_list->count();
        // // Paginate news_list
        // $news_list = $news_list->paginate($per_page, ['*'], 'page', $page_num);
        $new_donationArray = array();
        foreach ($donation_list as $row) {
            $row['created_datetime'] = DateHelper::dateToThaiFormat($row['created_at']);
            if ($row['paid_by'] == 1 && !empty($row['bank_id'])) {
                $bank_data = Bank::where('code', $row['bank_id'])->first();
                // dd($bank_data);
                if (!empty($bank_data)) {
                    $row['bank_name'] = $bank_data->name.' '.$bank_data->code;
                }
            }
            array_push($new_donationArray, $row);
        }
        $data['donation_list'] = $new_donationArray;
        // $data['max_page'] = ceil($num_rows / $per_page);
        //
        // if ($page_num > $data['max_page'] && $data['max_page'] != 0) {
        //     return redirect()->route('backend.news_manage', $data['max_page']);
        // }

        return view('backend.pages.donation_submit.donation_list', $data);
    }

    public function donationDetail(int $id = 1)
    {
        $this->isPermission();

        $data['page_th'] = 'รายละเอียดการบริจาค';
        $data['page_en'] = 'donation_detail';
        $data['donation_detail'] = DonationSubmit::where('id', $id)->first();
        $data['created_datetime'] = DateHelper::dateToThaiFormat($data['donation_detail']->created_at);
        if ($data['donation_detail']->paid_by == 1 && !empty($data['donation_detail']->bank_id)) {
            $bank_data = Bank::where('code', $data['donation_detail']->bank_id)->first();
            // dd($bank_data);
            if (!empty($bank_data)) {
                $data['bank_name'] = $bank_data->name.' '.$bank_data->code;
            }
        }

        $data['donation_detail']->mark_as_read = 1;
        $data['donation_detail']->save();

        return view('backend.pages.donation_submit.donation_detail', $data);
    }

    public function donationSubmitEmail(int $id = 1)
    {
        $this->isPermission();

        $data['donation_detail'] = DonationSubmit::where('id', $id)->first();
        $data['created_datetime'] = DateHelper::dateToThaiFormat($data['donation_detail']->created_at);
        if ($data['donation_detail']->paid_by == 1 && !empty($data['donation_detail']->bank_id)) {
            $bank_data = Bank::where('code', $data['donation_detail']->bank_id)->first();
            // dd($bank_data);
            if (!empty($bank_data)) {
                $data['bank_name'] = $bank_data->name.' '.$bank_data->code;
            }
        }

        return 0;
    }
}

resources/views/backend/layouts/modal.blade.php
<!-- Dialog box overlay -->
<div class="modal fade" id="modal_logout">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"> คุณแน่ใจที่จะออกจากระบบ ?</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-center"> หากคุณทำการกระทำใดอยู่แล้วยังไม่ได้บันทึก
        </br><p class="text-danger">การกระทำนั้นจะถูกยกเลิกทันที <i class="fas fa-times-circle"></i></p>
      <p>กด <b>ยกเลิก</b> เพื่อกลับสู่หน้าจัดการเว็บ</br>กด <b class="text-danger"><i class="fas fa-sign-out-alt"></i> ออกจากระบบ</b> เพื่อยืนยันการออกจากระบบ.</p>
      </div>

      <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-default" data-dismiss="modal">ยกเลิก</button>
        <form method="post" action="{{ route('auth.logout') }}">
          @csrf
        <button type="submit" class="btn btn-danger" onclick="return onLoad()"><i class="fas fa-sign-out-alt"></i> ออกจากระบบ</button>
      </form>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.Dialog box overlay End!! -->

<!-- Alert Delete -->
<div class="modal fade" id="modal-alert">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h4 class="modal-title"> <i class="fas fa-trash-alt"> </i>&nbsp&nbsp Delete this data ?</h4>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><br />คุณต้องการลบข้อมูลนี้ใช่หรือไม่ &hellip;</p>
      </div>
      <div class="modal-footer  justify-content-between">
        <button type="button" class="btn btn-default float-left" data-dismiss="modal" autofocus>ยกเลิก</button>
        <a id="modal_delete_btn" href="" onclick="onLoad()" style="color:#f56954;">
          <button type="button" class="btn btn-danger">ลบ</button>
        </a>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Alert Delete -->
<div class="modal fade" id="modal-news-alert">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h4 class="modal-title"> <i class="fas fa-trash-alt"> </i>&nbsp&nbsp Delete this news ?</h4>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><br />คุณต้องการลบข่าวนี้ใช่หรือไม่ &hellip;<br /><small class="text-danger">โดยภาพสไลด์ของข่าวนี้จะถูกลบทั้งหมดด้วย</br>การกระทำนี้ไม่สามารถย้อนกลับได้</small></p>
      </div>
      <div class="modal-footer  justify-content-between">
        <button type="button" class="btn btn-default float-left" data-dismiss="modal" autofocus>ยกเลิก</button>
        <a id="modal_delete_news_btn" href="" onclick="onLoad()" style="color:#f56954;">
          <button type="button" class="btn btn-danger">ลบ</button>
        </a>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Alert Delete -->
<div class="modal fade" id="modal-project-alert">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h4 class="modal-title"> <i class="fas fa-trash-alt"> </i>&nbsp&nbsp Delete this project ?</h4>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><br/>คุณต้องการลบข้อมูลโครงการนี้ใช่หรือไม่ &hellip;<br /><small class="text-danger">โดยภาพสไลด์ของโครงการนี้จะถูกลบทั้งหมดด้วย</small></p>
      </div>
      <div class="modal-footer  justify-content-between">
        <button type="button" class="btn btn-default float-left" data-dismiss="modal" autofocus>ยกเลิก</button>
        <a id="modal_delete_project_btn" href="" onclick="onLoad()" style="color:#f56954;">
          <button type="button" class="btn btn-danger">ลบ</button>
        </a>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Alert  -->
<div class="modal modal-danger fade" id="modal-file">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-info">
        <h4 class="modal-title"> <i class="fas fa-file-upload"> </i>&nbsp&nbsp File upload size too large ?</h4>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p><br /><i class="fas fa-info-circle text-info mt-3 mr-2" style="font-size:1.5rem;"> </i> ไฟล์ของท่านมีขนาดใหญ่เกินที่กำหนด &hellip;<br/><small class="ml-5 text-danger">สามารถอัปโหลดได้ไม่เกิน</small><span class="text-danger"> 2 MB.</span></small></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info pull-right" data-dismiss="modal" autofocus>ตกลง</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Alert  -->
<div class="modal modal-danger fade" id="modal-image">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-info">
        <h4 class="modal-title"> <i class="fas fa-file-image"> </i>&nbsp&nbsp Image file upload size too large ?</h4>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p><br /><i class="fas fa-info-circle text-info mt-3 mr-2" style="font-size:1.5rem;"> </i> ไฟล์รูปของท่านมีขนาดใหญ่เกินที่กำหนด &hellip;<br/><small class="ml-5 text-danger">สามารถอัปโหลดได้ไม่เกิน</small><span class="text-danger"> 2 MB.</span></small></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info pull-right" data-dismiss="modal" autofocus>ตกลง</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Alert slide image overload size (2MB) -->
<div class="modal modal-danger fade" id="modal-slide-alert">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h4 class="modal-title"> <i class="fas fa-file-upload"> </i>&nbsp&nbsp File upload size too large ?</h4>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p><br /><i class="fas fa-info-circle text-info mt-3 mr-2" style="font-size:1.5rem;"> </i> ไฟล์ของท่านมีขนาดใหญ่เกินที่กำหนด &hellip;<br/><small class="ml-5 text-danger">สามารถอัปโหลดได้ไม่เกิน</small><span class="text-danger"> 8 MB.</span></small></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info pull-right" data-dismiss="modal" autofocus>ตกลง</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

resources/views/backend/layouts/onLoad.blade.php
<div id="loader_spinner" style="display: none;position: fixed;height:200%;width:100%; z-index:5000;background-color: rgba(0,0,0,.6)">
  <i class="fas fa-spinner fa-spin text-white" style="font-size:3rem;z-index:2000;margin-top:calc(50vh - 1.5rem);margin-left:calc(50vw - 1.5rem)"></i>
</div>

<div id="loader_spinner2" style="display: block;position: fixed;height:200%;width:100%; z-index:5000;background-color: rgba(0,0,0,.6)">
  <i class="fas fa-spinner fa-spin text-white" style="font-size:3rem;z-index:2000;margin-top:calc(50vh - 1.5rem);margin-left:calc(50vw - 1.5rem)"></i>
</div>

resources/views/backend/layouts/topnav.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{{ route('backend.dashboard') }}" onclick="onLoad('{{ route('backend.dashboard') }}')" class="nav-link">หน้าหลัก</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{{ route('home') }}" class="nav-link" target="_blank">เว็บไซต์ Manna <i class="fas fa-external-link-alt"></i> </a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-user-circle" style="font-size: 1.3rem"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">

        <div class="dropdown-divider"></div>
        <a onclick="onLoad('{{ route('admin.reset_password') }}')" href="{{ route('admin.reset_password') }}" class="dropdown-item onload">
          <i class="fas fa-key mr-2"></i> ตั้งรหัสผ่านใหม่
        </a>

        @if(Auth::guard('admin')->user()->isPermission1())
        <div class="dropdown-divider"></div>
        <a onclick="onLoad('{{ route('admin.admin_manage') }}')" href="{{ route('admin.admin_manage') }}" class="dropdown-item onload">
          <i class="fas fa-users mr-2"></i> จัดการผู้ดูแลเว็บ<small class="float-right text-gray mt-1">บันทึกการใช้งาน</small>
        </a>
        @endif

        <div class="dropdown-divider"></div>
        <button type="button" class="dropdown-item bg-danger onload" data-toggle="modal" data-target="#modal_logout">
          <i class="fas fa-sign-out-alt mr-2"></i> ออกจากระบบ
        </button>

      </div>
    </li>
  </ul>
</nav>
<!-- /.navbar -->