routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your donation. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache & Route is cleared";
});

// ------------------------ Front-End -------------------------------------
Route::get('/', 'frontend\Home@index')->name('index');
Route::get('/home', 'frontend\Home@index')->name('home');

Route::get('/about', 'frontend\About@index')->name('about');

Route::get('/news_acts/{page_num}', 'frontend\NewsActs@index')->name('news_acts');
Route::get('/news_acts/detail/{page_num}/{id}', 'frontend\NewsActs@detail')->name('news_acts_detail');
Route::get('/news_acts/detail/{id}/gallery', 'frontend\NewsActs@gallery')->name('news_acts_gallery');

Route::get('/contact', 'frontend\Contact@index')->name('contact');

Route::get('/donation', 'frontend\Donation@index')->name('donation');

Route::group(['middleware'=>['XSS']], function () { // ดัก script ใน Form
    Route::post('/contact_submit', 'frontend\Contact@contactSubmit')->name('contact_submit');
    Route::post('/donation_submit', 'frontend\Donation@donationSubmit')->name('donation_submit');
});

// ------------------------ .end Front-End -------------------------------------

// ------------------------ Back-End -------------------------------------
//Auth Routes
Auth::routes();
Route::prefix('/@backend')->name('auth.')->namespace('Admin\Auth')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.auth');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

// Admin manage route
Route::prefix('/@backend')->name('admin.')->namespace('Admin')->middleware('auth:admin')->group(function () {
    Route::get('/reset_password', 'ResetPasswordController@showResetPasswordForm')->name('reset_password');
    Route::post('/reset_password/update', 'ResetPasswordController@update')->name('reset_password.update');
    // Super Admin only
    Route::get('/admin_manage', 'ManageAdminsController@index')->name('admin_manage');
    Route::get('/admin_manage/create_form', 'ManageAdminsController@createForm')->name('admin_manage.create_form');
    Route::post('/admin_manage/create', 'ManageAdminsController@create')->name('admin_manage.create');
    Route::get('/admin_manage/edit_form/{id}', 'ManageAdminsController@editForm')->name('admin_manage.edit_form');
    Route::post('/admin_manage/edit', 'ManageAdminsController@edit')->name('admin_manage.edit');
    Route::get('/admin_manage/logging/{id}', 'LogsController@index')->name('admin_manage.logging');
});

Route::prefix('/@backend')->name('backend.')->namespace('backend')->middleware('auth:admin')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    // Home route
    Route::get('/home/banner_edit_form', 'HomeController@bannerEditForm')->name('home_banner_edit_form');
    Route::post('/home/banner_edit', 'HomeController@bannerEdit')->name('home_banner_edit');
    Route::get('/home/about_edit_form', 'HomeController@aboutEditForm')->name('home_about_edit_form');
    Route::post('/home/about_edit', 'HomeController@aboutEdit')->name('home_about_edit');
    Route::get('/home/help_edit_form', 'HomeController@helpEditForm')->name('home_help_edit_form');
    Route::post('/home/help_edit', 'HomeController@helpEdit')->name('home_help_edit');
    Route::get('/home/divider_edit_form', 'HomeController@dividerEditForm')->name('home_divider_edit_form');
    Route::post('/home/divider_edit', 'HomeController@dividerEdit')->name('home_divider_edit');
    // About us route
    Route::get('/about_us/banner_edit_form', 'AboutController@aboutBannerEditForm')->name('about_banner_edit_form');
    Route::post('/about_us/banner_edit', 'AboutController@aboutBannerEdit')->name('about_banner_edit');
    Route::get('/about_us/who_we_are_edit_form', 'AboutController@aboutWhoWeAreEditForm')->name('about_who_we_are_edit_form');
    Route::post('/about_us/who_we_are_edit', 'AboutController@aboutWhoWeAreEdit')->name('about_who_we_are_edit');
    Route::get('/about_us/what_we_do_edit_form', 'AboutController@aboutWhatWeDoEditForm')->name('about_what_we_do_edit_form');
    Route::post('/about_us/what_we_do_edit', 'AboutController@aboutWhatWeDoEdit')->name('about_what_we_do_edit');
    // News route
    Route::get('/news/banner_edit_form', 'NewsController@newsBannerEditForm')->name('news_banner_edit_form');
    Route::post('/news/banner_edit', 'NewsController@newsBannerEdit')->name('news_banner_edit');
    Route::get('/news_manage/{page_num}', 'NewsController@newsManage')->name('news_manage');
    Route::get('/news_manage/{page_num}/add_form', 'NewsController@addNewsForm')->name('news_add_form');
    Route::post('/news_manage/add', 'NewsController@addNews')->name('news_add');
    Route::get('/news_manage/{page_num}/edit_form/{id}', 'NewsController@newsEditForm')->name('news_edit_form');
    Route::post('/news_manage/edit', 'NewsController@newsEdit')->name('news_edit');
    // News route - dropzone upload image
    Route::post('/news_manage/upload_news_gallery', 'NewsController@uploadNewsImageDropzone')->name('upload_gallery_image');
    Route::post('/news_manage/load_news_gallery_list', 'NewsController@setImageListPreview')->name('load_news_gallery_list');
    Route::post('/news_manage/remove_news_gallery', 'NewsController@removeNewsGalleryImage')->name('delete_news_image_attache');
    // .end dropzone upload image
    Route::get('/news_manage/{page_num}/hide/{id}', 'NewsController@hideNews')->name('hide_news');
    Route::get('/news_manage/{page_num}/show/{id}', 'NewsController@showNews')->name('show_news');
    Route::get('/news_manage/{page_num}/remove/{id}', 'NewsController@removeNews')->name('remove_news');
    // Contact us route
    Route::get('/contact_us/banner_edit_form', 'ContactController@contactBannerEditForm')->name('contact_banner_edit_form');
    Route::post('/contact_us/banner_edit', 'ContactController@contactBannerEdit')->name('contact_banner_edit');
    Route::get('/contact_us/data_edit_form', 'ContactController@contactDataEditForm')->name('contact_data_edit_form');
    Route::post('/contact_us/data_edit', 'ContactController@contactDataEdit')->name('contact_data_edit');
    // Footer us route
    Route::get('/footer/edit_form', 'ContactController@footerEditForm')->name('footer_edit_form');
    Route::post('/footer/edit', 'ContactController@footerEdit')->name('footer_edit');
    // Donation route
    Route::get('/donation/banner_edit_form', 'DonationController@donationBannerEditForm')->name('donation_banner_edit_form');
    Route::post('/donation/banner_edit', 'DonationController@donationBannerEdit')->name('donation_banner_edit');
    Route::get('/donation/how_you_can_help_edit_form', 'DonationController@donationHowYouCanHelpEditForm')->name('donation_how_you_can_help_edit_form');
    Route::post('/donation/how_you_can_help_edit', 'DonationController@donationHowYouCanHelpEdit')->name('donation_how_you_can_help_edit');
    // Contact Person route
    Route::get('/contact_submit/list/{filter?}', 'ContactSubmitController@contactList')->name('contact_list');
    // Donation route
    Route::get('/donation_submit/list/{filter?}', 'DonationSubmitController@donationList')->name('donation_list');
    Route::get('/donation_submit/detail/{id}/{filter?}', 'DonationSubmitController@donationDetail')->name('donation_detail');

    // File Upload
    Route::get('/file_upload', 'FileUploadController@index')->name('file_upload');
    Route::post('/file_upload/upload', 'FileUploadController@fileUpload')->name('file_upload.upload');
    Route::get('/file_upload/download/{id}', 'FileUploadController@downloadFile')->name('file_upload.download');
    Route::get('/file_upload/remove/{id}', 'FileUploadController@removeFile')->name('file_upload.remove');
});

// ------------------------ .end Back-End -------------------------------------

app/DonationSubmit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DonationSubmit extends Model
{
    protected $table = 'donate_submit';

    protected $primaryKey = 'id';

    protected $fillable = [
      'first_name',
      'last_name',
      'email',
      'donate_for',
      'paid_by',
      'bank_id',
      'bank_other',
      'bank_branch',
      'date',
      'money_amount',
      'attache_file',
    ];

    protected $hidden = [
      'created_at',
    ];
}

app/Http/Controllers/backend/DonationSubmitController.php
<?php

namespace App\Http\Controllers\backend;

use Auth;

use App\DonationSubmit;
use App\Bank;
use App\Helper\DateHelper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DonationSubmitController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function isPermission()
    {
        if (!Auth::guard('admin')->user()->isPermission4()) {
            return Redirect::to('@backend/dashboard')->send()->with(array('alert' => 'toast','type' => 'error','message' => '&nbsp&nbsp คุณไม่ได้รับสิทธ์ให้เข้าถึง'));
        }
    }

    public function donationList()
    {
        $this->isPermission();

        // $per_page = 10;
        // $data['page_num'] = $page_num;

        $data['page_th'] = 'ข้อมูลการบริจาค';
        $data['page_en'] = 'donation_list';
        $donation_list = DonationSubmit::orderBy('created_at', 'desc')->get();
        // dd($news_list->get());

        // $num_rows = $news_list->count();
        // // Paginate news_list
        // $news_list = $news_list->paginate($per_page, ['*'], 'page', $page_num);
        $new_donationArray = array();
        foreach ($donation_list as $row) {
            $row['created_datetime'] = DateHelper::dateToThaiFormat($row['created_at']);
            if ($row['paid_by'] == 1 && !empty($row['bank_id'])) {
                $bank_data = Bank::where('code', $row['bank_id'])->first();
                // dd($bank_data);
                if (!empty($bank_data)) {
                    $row['bank_name'] = $bank_data->name.' '.$bank_data->code;
                }
            }
            array_push($new_donationArray, $row);
        }
        $data['donation_list'] = $new_donationArray;
        // $data['max_page'] = ceil($num_rows / $per_page);
        //
        // if ($page_num > $data['max_page'] && $data['max_page'] != 0) {
        //     return redirect()->route('backend.news_manage', $data['max_page']);
        // }

        return view('backend.pages.donation_submit.donation_list', $data);
    }

    public function donationDetail(int $id = 1)
    {
        $this->isPermission();

        $data['page_th'] = 'รายละเอียดการบริจาค';
        $data['page_en'] = 'donation_detail';
        $data['donation_detail'] = DonationSubmit::where('id', $id)->first();
        $data['created_datetime'] = DateHelper::dateToThaiFormat($data['donation_detail']->created_at);
        if ($data['donation_detail']->paid_by == 1 && !empty($data['donation_detail']->bank_id)) {
            $bank_data = Bank::where('code', $data['donation_detail']->bank_id)->first();
            // dd($bank_data);
            if (!empty($bank_data)) {
                $data['bank_name'] = $bank_data->name.' '.$bank_data->code;
            }
        }

        $data['donation_detail']->mark_as_read = 1;
        $data['donation_detail']->save();

        return view('backend.pages.donation_submit.donation_detail', $data);
    }

    public function donationSubmitEmail(int $id = 1)
    {
        $this->isPermission();

        $data['donation_detail'] = DonationSubmit::where('id', $id)->first();
        $data['created_datetime'] = DateHelper::dateToThaiFormat($data['donation_detail']->created_at);
        if ($data['donation_detail']->paid_by == 1 && !empty($data['donation_detail']->bank_id)) {
            $bank_data = Bank::where('code', $data['donation_detail']->bank_id)->first();
            // dd($bank_data);
            if (!empty($bank_data)) {
                $data['bank_name'] = $bank_data->name.' '.$bank_data->code;
            }
        }

        return 0;
    }
}

resources/views/backend/pages/donation_submit/donation_detail.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('backend.layouts.header')

<!-- Body -->
<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

@include('backend.layouts.topnav')
@include('backend.layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark"><i class="fas fa-envelope"></i> {{ $page_th }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <!-- <li class="breadcrumb-item"><a href="{{ route('backend.dashboard') }}">Home</a></li> -->
            <li class="breadcrumb-item active">{{ $page_th }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
      <section class="content">

        <div class="card card-info">
          <div class="card-header">
            <h3 class="card-title">{{ $page_th }}</h3>
            <button type="button" onclick="onLoad('{{ route('backend.donation_list') }}')" class="btn btn-default btn-sm float-right">
                <i class="fas fa-chevron-left"> ย้อนกลับ</i>
            </button>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-3 font-weight-bold text-md-right text-left">
                เวลาที่ส่งข้อมูล
              </div>
              <div class="col-md-9">
                {!! $created_datetime !!}
              </div>

              <div class="col-md-3 font-weight-bold text-md-right text-left">
                ชื่อ-นามสกุล
              </div>
              <div class="col-md-9">
                {{ $donation_detail->first_name }} {{ $donation_detail->last_name }}
              </div>

              <div class="col-md-3 font-weight-bold text-md-right text-left">
                อีเมล
              </div>
              <div class="col-md-9">
                @if(!empty($donation_detail->email)) {{ $donation_detail->email }} @else - @endif
              </div>

              <div class="col-md-3 font-weight-bold text-md-right text-left">
                บริจาคเพื่อ
              </div>
              <div class="col-md-9">
                @if(!empty($donation_detail->donate_for)) {{ $donation_detail->donate_for }} @else - @endif
              </div>

              <div class="col-md-3 font-weight-bold text-md-right text-left">
                จำนวนเงิน
              </div>
              <div class="col-md-9">
                @if(!empty($donation_detail->money_amount)) {{ number_format($donation_detail->money_amount, 0) }} บาท @else - @endif
              </div>

              <div class="col-md-3 font-weight-bold text-md-right text-left mt-3">
                ชำระโดย
              </div>
              <div class="col-md-9 mt-3">
                @if($donation_detail->paid_by == 0) เงินสด @elseif($donation_detail->paid_by == 1) โอนผ่านธนาคาร @endif
              </div>

              @if($donation_detail->paid_by == 1)
                <div class="col-md-3 font-weight-bold text-md-right text-left">
                  ธนาคาร
                </div>
                <div class="col-md-9">
                  {{ $bank_name }}
                </div>

                @if(!empty($donation_detail->bank_other))
                <div class="col-md-3 font-weight-bold text-md-right text-left">
                  ธนาคารอื่นๆ ระบุ
                </div>
                <div class="col-md-9">
                  {{ $donation_detail->bank_other }}
                </div>
                @endif

                <div class="col-md-3 font-weight-bold text-md-right text-left">
                  สาขา
                </div>
                <div class="col-md-9">
                  {{ $donation_detail->bank_branch }}
                </div>

                <div class="col-md-3 font-weight-bold text-md-right text-left">
                  วันที่และเวลาโอนเงิน
                </div>
                <div class="col-md-9">
                  {!! App\Helper\DateHelper::dateToThaiFormat($donation_detail->date) !!}
                </div>

                @if(!empty($donation_detail->attache_file))
                <div class="col-md-3 font-weight-bold text-md-right text-left">
                  หลักฐานการโอนเงิน
                </div>
                <div class="col-md-9">
                  <a href="{{ config('app.url').'files_upload/donate_attaches/'.$donation_detail->attache_file }}" target="_blank">เปิดไฟล์ในแท็บใหม่ <small><i class="fas fa-external-link-alt"></i></small> </a>
                </div>
                @endif
              @endif
            </div>

          </div>
          <!-- /.card-body -->

        </div>
        <!-- /.card -->

        @include('backend.layouts.modal')

      </section>
      <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@include('backend.layouts.footer')

</div>
<!-- ./wrapper -->
<script type="text/javascript">

</script>
</body>
</html>

resources/views/backend/pages/donation_submit/donation_list.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('backend.layouts.header')

<style media="screen">
  #donation_table_filter {
    float: right;
  }

  #donation_table_paginate {
    float: right;
  }
</style>

<!-- Body -->
<body onload="onLoadBody()" class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

@include('backend.layouts.topnav')
@include('backend.layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark"><i class="fas fa-envelope"></i> {{ $page_th }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <!-- <li class="breadcrumb-item"><a href="{{ route('backend.dashboard') }}">Home</a></li> -->
            <li class="breadcrumb-item active">{{ $page_th }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
      <section class="content">

        <div class="card">
          <div class="card-header">
            <h3 class="card-title">ตาราง : {{ $page_th }} </h3>
          </div>
          <div class="card-body">
            <table id="donation_table" class="table table-bordered table-hover table-responsive display" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th class="all" style="min-width:50px;width:50px;">ดูข้อมูล</th>
                  <th class="all" style="min-width:105px;width:105px;max-width:105px" width="105">วันที่ส่งข้อมูล</br> <small>ปี/เดือน/วัน</small> </th>
                  <th class="all" style="min-width:200px;width:auto;">ชื่อ-นามสกุล</th>
                  <th class="all" style="min-width:200px;width:auto;">อีเมล</th>
                  <th class="all text-right" style="min-width:200px;width:auto;">จำนวนเงิน (บาท)</th>
                  <th class="all d-none" style="min-width:200px;width:auto;">บริจาคเพื่อ</th>
                  <th class="all" style="min-width:200px;width:auto;">ชำระโดย</th>
                  <th class="all d-none" style="min-width:200px;width:auto;">ข้อมูลการโอนเงิน (กรณีโอนเงิน)</th>
                  <th class="all d-none" style="min-width:200px;width:auto;">ไฟล์แนบ (กรณีโอนเงิน)</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>ดูข้อมูล</th>
                  <th>วันที่ส่งข้อมูล</th>
                  <th>ชื่อ-นามสกุล</th>
                  <th>อีเมล</th>
                  <th class="text-right">จำนวนเงิน (บาท)</th>
                  <th class="all d-none">บริจาคเพื่อ</th>
                  <th>ชำระโดย</th>
                  <th class="all d-none">ข้อมูลการโอนเงิน (กรณีโอนเงิน)</th>
                  <th class="all d-none">ไฟล์แนบ (กรณีโอนเงิน)</th>
                </tr>
              </tfoot>
              <tbody>
                <!-- Loop donation table -->
                @foreach ($donation_list as $row)
                  <tr>
                    <td>
                      <a href="{{ route('backend.donation_detail', $row['id']) }}">
                        <i class="fas fa-search text-info"></i>
                        @if($row['mark_as_read'] == 0)
                        <small class="badge badge-warning">NEW</small>
                        @endif
                      </a>
                    </td>
                    <td>
                      <p class="d-none">{{ $row['created_at'] }}</p>
                      {!! App\Helper\DateHelper::dateTimeToSlashFormat($row['created_at']) !!}
                    </td>
                    <td>
                      {{ $row['first_name'] }} {{ $row['last_name'] }}
                    </td>
                    <td>
                      @if(!empty($row['email'])) {{ $row['email'] }} @else - @endif
                    </td>
                    <td class="text-right">
                      {{ number_format($row['money_amount'], 0) }}
                    </td>
                    <td class="d-none">
                      @if(!empty($row['donate_for'])) {{ $row['donate_for'] }} @else - @endif
                    </td>
                    <td>
                      @if($row['paid_by'] == 0) เงินสด @elseif($row['paid_by'] == 1) โอนผ่านธนาคาร @endif
                    </td>
                    <td class="d-none">
                      @if($row['paid_by'] == 0) -
                      @elseif($row['paid_by'] == 1)
                        @if(!empty($row['bank_name'])) ชื่อธนาคาร : {{ $row['bank_name'] }} @endif @if(!empty($row['bank_other'])) ธนาคารอื่นๆ ระบุชื่อธนาคาร : {{ $row['bank_other'] }} @endif @if(!empty($row['bank_branch'])) สาขา : {{ $row['bank_branch'] }} @endif @if(!empty($row['date'])) {!! App\Helper\DateHelper::dateToThaiFormat($row['date']) !!} @endif
                      @endif
                    </td>
                    <td class="d-none">
                      @if(!empty($row['attache_file'])) <a href="{{ config('app.url').'files_upload/donate_attaches/'.$row['attache_file'] }}">{{ config('app.url').'files_upload/donate_attaches/'.$row['attache_file'] }}</a> @else - @endif
                    </td>
                  </tr>
                  @endforeach
                  <!-- End loop users table -->
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->

        @include('backend.layouts.modal')

      </section>
      <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@include('backend.layouts.footer')

</div>
<!-- ./wrapper -->
<script type="text/javascript">
    $("#donation_table").DataTable({
          'stateSave': true,  // Awesome that can remember page of dataTable
          'ordering': true,
          'searching': true,
          "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
          "lengthChange" : true, //thought this line could hide the LengthMenu
          dom: 'Bfrtip',
          buttons: [
            'excel',
          ],
          // 'scrollX': true,
           'language': {"decimal": "",
               "emptyTable":     "ยังไม่มีข้อมูล",
               "info":           "แสดงลำดับ _START_ ถึง _END_ จาก _TOTAL_ ข้อมูล",
               "infoEmpty":      "แสดงลำดับที่ 0 ถึง 0 จาก 0 ข้อมูล",
               "infoFiltered":   "(กรองข้อมูลจาก _MAX_ ข้อมูลทั้งหมด)",
               "infoPostFix":    "",
               "thousands":      ",",
               "lengthMenu":     "แสดง _MENU_ &nbspข้อมูล",
               "loadingRecords": "กำลังโหลด...",
               "processing":     "กำลังประมวลผล...",
               "search":         "ค้นหา:",
               "zeroRecords":    "ไม่ตรงกับข้อมูลใดๆ",
               "paginate": {
                   "first":      "แรก",
                   "last":       "สุดท้าย",
                   "next":       "ถัดไป",
                   "previous":   "ก่อนหน้า"
               },
               "aria": {
                   "sortAscending":  ": activate to sort column ascending",
                   "sortDescending": ": activate to sort column descending"
               },
             },
    });
</script>
</body>
</html>